# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 897ddfbed2e3689d56494969d604d472079d821d90bb2b09da30e1a69c89cc965428b8cec0b4adced71af11710570462f1e00f35167248f444078cff7d14a4ea

test:
  secret_key_base: bae6c0ec2091d374b4337a9a593db0ad6a4714a50088377e995c9e8108a91c3bb1632e42371c784844ee933f80ca6c6b51aa9e4dd6b4f19decd673555207cc01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
